services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ollama
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tasks

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"